@{
    ModuleVersion     = '0.2.1'
    RootModule        = 'obs-powershell.psm1'
    Description       = 'Script your streams'
    Guid              = '1417123e-a932-439f-9b68-a7313cf1e170'
    Author            = 'James Brundage'
    CompanyName       = 'Start-Automating'
    Copyright         = '2022-2026 Start-Automating'
    FormatsToProcess  = 'obs-powershell.format.ps1xml'
    TypesToProcess    = 'obs-powershell.types.ps1xml'
    PowerShellVersion = '7.0'
    PrivateData = @{
        PSData = @{
            Tags = 'PowerShell', 'OBS'
            ProjectURI = 'https://github.com/StartAutomating/obs-powershell'
            LicenseURI = 'https://github.com/StartAutomating/obs-powershell/blob/main/LICENSE'
            ReleaseNotes = @'
## obs-powershell 0.2.1:

* New General Purpose Commands
  * Start-OBS (#220)
  * Stop-OBS (#226)
* New Shader Commands:
  * Get-OBS3dPanelShader
  * Get-OBSAudioShader
  * Get-OBSCubeRotatingShader
  * Get-OBSDisplacementMapAdvancedInvertShader
  * Get-OBSDisplacementMapAdvancedShader
  * Get-OBSDisplacementMapInvertShader
  * Get-OBSDisplacementMapShader
  * Get-OBSGlitchPeriodicShader
  * Get-OBSHardBlinkShader
  * Get-OBSMotionBlurShader
  * Get-OBSNoiseShader
  * Get-OBSNormalMapShader
  * Get-OBSPerspectiveShader
  * Get-OBSQuadrilateralCropShader
  * Get-OBSRepeatGridCenterCropShader
  * Get-OBSWalkingDeadPixelFixerShader
  * Get-OBSZoomBlurTransitionShader

---

> Like It? [Star It](https://github.com/StartAutomating/obs-powershell)
> Love It? [Support It](https://github.com/sponsors/StartAutomating)


Additional History available in the [CHANGELOG](https://github.com/StartAutomating/obs-powershell/blob/main/CHANGELOG.md)
'@
        }
    }
    FunctionsToExport = 'Clear-OBSScene',
'Connect-OBS',
'Disconnect-OBS',
'Get-OBS',
'Hide-OBS',
'Receive-OBS',
'Remove-OBS',
'Send-OBS',
'Show-OBS',
'Start-OBS',
'Stop-OBS',
'Watch-OBS',
'Set-OBS3DFilter',
'Set-OBSColorFilter',
'Set-OBSEqualizerFilter',
'Set-OBSGainFilter',
'Set-OBSRenderDelayFilter',
'Set-OBSScaleFilter',
'Set-OBSScrollFilter',
'Set-OBSShaderFilter',
'Set-OBSSharpnessFilter',
'Get-OBSEffect',
'Import-OBSEffect',
'Remove-OBSEffect',
'Start-OBSEffect',
'Stop-OBSEffect',
'Add-OBSInput',
'Add-OBSProfile',
'Add-OBSScene',
'Add-OBSSceneCollection',
'Add-OBSSceneItem',
'Add-OBSSourceFilter',
'Copy-OBSSceneItem',
'Get-OBSCurrentPreviewScene',
'Get-OBSCurrentProgramScene',
'Get-OBSCurrentSceneTransition',
'Get-OBSCurrentSceneTransitionCursor',
'Get-OBSGroup',
'Get-OBSGroupSceneItem',
'Get-OBSHotkey',
'Get-OBSInput',
'Get-OBSInputAudioBalance',
'Get-OBSInputAudioMonitorType',
'Get-OBSInputAudioSyncOffset',
'Get-OBSInputAudioTracks',
'Get-OBSInputDefaultSettings',
'Get-OBSInputKind',
'Get-OBSInputMute',
'Get-OBSInputPropertiesListPropertyItems',
'Get-OBSInputSettings',
'Get-OBSInputVolume',
'Get-OBSLastReplayBufferReplay',
'Get-OBSMediaInputStatus',
'Get-OBSMonitor',
'Get-OBSOutput',
'Get-OBSOutputSettings',
'Get-OBSOutputStatus',
'Get-OBSPersistentData',
'Get-OBSProfile',
'Get-OBSProfileParameter',
'Get-OBSRecordDirectory',
'Get-OBSRecordStatus',
'Get-OBSReplayBufferStatus',
'Get-OBSScene',
'Get-OBSSceneCollection',
'Get-OBSSceneItem',
'Get-OBSSceneItemBlendMode',
'Get-OBSSceneItemEnabled',
'Get-OBSSceneItemId',
'Get-OBSSceneItemIndex',
'Get-OBSSceneItemLocked',
'Get-OBSSceneItemSource',
'Get-OBSSceneItemTransform',
'Get-OBSSceneSceneTransitionOverride',
'Get-OBSSceneTransition',
'Get-OBSSourceActive',
'Get-OBSSourceFilter',
'Get-OBSSourceFilterDefaultSettings',
'Get-OBSSourceFilterKind',
'Get-OBSSourceFilterList',
'Get-OBSSourceScreenshot',
'Get-OBSSpecialInputs',
'Get-OBSStats',
'Get-OBSStreamServiceSettings',
'Get-OBSStreamStatus',
'Get-OBSStudioModeEnabled',
'Get-OBSTransitionKind',
'Get-OBSVersion',
'Get-OBSVideoSettings',
'Get-OBSVirtualCamStatus',
'Open-OBSInputFiltersDialog',
'Open-OBSInputInteractDialog',
'Open-OBSInputPropertiesDialog',
'Open-OBSSourceProjector',
'Open-OBSVideoMixProjector',
'Remove-OBSInput',
'Remove-OBSProfile',
'Remove-OBSScene',
'Remove-OBSSceneItem',
'Remove-OBSSourceFilter',
'Resume-OBSRecord',
'Save-OBSReplayBuffer',
'Save-OBSSourceScreenshot',
'Send-OBSCallVendorRequest',
'Send-OBSCustomEvent',
'Send-OBSOffsetMediaInputCursor',
'Send-OBSPauseRecord',
'Send-OBSPressInputPropertiesButton',
'Send-OBSSleep',
'Send-OBSStreamCaption',
'Send-OBSTriggerHotkeyByKeySequence',
'Send-OBSTriggerHotkeyByName',
'Send-OBSTriggerMediaInputAction',
'Send-OBSTriggerStudioModeTransition',
'Set-OBSCurrentPreviewScene',
'Set-OBSCurrentProfile',
'Set-OBSCurrentProgramScene',
'Set-OBSCurrentSceneCollection',
'Set-OBSCurrentSceneTransition',
'Set-OBSCurrentSceneTransitionDuration',
'Set-OBSCurrentSceneTransitionSettings',
'Set-OBSInputAudioBalance',
'Set-OBSInputAudioMonitorType',
'Set-OBSInputAudioSyncOffset',
'Set-OBSInputAudioTracks',
'Set-OBSInputMute',
'Set-OBSInputName',
'Set-OBSInputSettings',
'Set-OBSInputVolume',
'Set-OBSMediaInputCursor',
'Set-OBSOutputSettings',
'Set-OBSPersistentData',
'Set-OBSProfileParameter',
'Set-OBSRecordDirectory',
'Set-OBSSceneItemBlendMode',
'Set-OBSSceneItemEnabled',
'Set-OBSSceneItemIndex',
'Set-OBSSceneItemLocked',
'Set-OBSSceneItemTransform',
'Set-OBSSceneName',
'Set-OBSSceneSceneTransitionOverride',
'Set-OBSSourceFilterEnabled',
'Set-OBSSourceFilterIndex',
'Set-OBSSourceFilterName',
'Set-OBSSourceFilterSettings',
'Set-OBSStreamServiceSettings',
'Set-OBSStudioModeEnabled',
'Set-OBSTBarPosition',
'Set-OBSVideoSettings',
'Start-OBSOutput',
'Start-OBSRecord',
'Start-OBSReplayBuffer',
'Start-OBSStream',
'Start-OBSVirtualCam',
'Stop-OBSOutput',
'Stop-OBSRecord',
'Stop-OBSReplayBuffer',
'Stop-OBSStream',
'Stop-OBSVirtualCam',
'Switch-OBSInputMute',
'Switch-OBSOutput',
'Switch-OBSRecord',
'Switch-OBSRecordPause',
'Switch-OBSReplayBuffer',
'Switch-OBSStream',
'Switch-OBSVirtualCam',
'Get-OBS3dPanelShader',
'Get-OBS3dSwapTransitionShader',
'Get-OBSAddShader',
'Get-OBSAlphaBorderShader',
'Get-OBSAlphaGamingBentCameraShader',
'Get-OBSAnimatedPathShader',
'Get-OBSAnimatedTextureShader',
'Get-OBSAsciiShader',
'Get-OBSAspectRatioShader',
'Get-OBSAudioShader',
'Get-OBSBackgroundRemovalShader',
'Get-OBSBlendOpacityShader',
'Get-OBSBlinkShader',
'Get-OBSBloomShader',
'Get-OBSBorderShader',
'Get-OBSBoxBlurShader',
'Get-OBSBulgePinchShader',
'Get-OBSBurnShader',
'Get-OBSCartoonShader',
'Get-OBSCellShadedShader',
'Get-OBSChromaticAberrationShader',
'Get-OBSChromaUVDistortionShader',
'Get-OBSCircleMaskFilterShader',
'Get-OBSClockAnalogShader',
'Get-OBSClockDigitalLedShader',
'Get-OBSClockDigitalNixieShader',
'Get-OBSColorDepthShader',
'Get-OBSColorGradeFilterShader',
'Get-OBSCornerPinShader',
'Get-OBSCrtCurvatureShader',
'Get-OBSCubeRotatingShader',
'Get-OBSCurveShader',
'Get-OBSCutRectPerCornerShader',
'Get-OBSCylinderShader',
'Get-OBSDarkenShader',
'Get-OBSDeadPixelFixerShader',
'Get-OBSDensitySatHueShader',
'Get-OBSDiffuseTransitionShader',
'Get-OBSDigitalRainShader',
'Get-OBSDisplacementMapAdvancedInvertShader',
'Get-OBSDisplacementMapAdvancedShader',
'Get-OBSDisplacementMapInvertShader',
'Get-OBSDisplacementMapShader',
'Get-OBSDivideRotateShader',
'Get-OBSDoodleShader',
'Get-OBSDrawingsShader',
'Get-OBSDropShadowShader',
'Get-OBSDrunkShader',
'Get-OBSDynamicMaskShader',
'Get-OBSEdgeDetectionShader',
'Get-OBSEmbersShader',
'Get-OBSEmbossColorShader',
'Get-OBSEmbossShader',
'Get-OBSExeldroBentCameraShader',
'Get-OBSFadeTransitionShader',
'Get-OBSFillColorGradientShader',
'Get-OBSFillColorLinearShader',
'Get-OBSFillColorRadialDegreesShader',
'Get-OBSFillColorRadialPercentageShader',
'Get-OBSFilterTemplateShader',
'Get-OBSFire3Shader',
'Get-OBSFireShader',
'Get-OBSFireworks2Shader',
'Get-OBSFireworksShader',
'Get-OBSFisheyeShader',
'Get-OBSFisheyeXyShader',
'Get-OBSFlipShader',
'Get-OBSFrostedGlassShader',
'Get-OBSGammaCorrectionShader',
'Get-OBSGaussianBlurAdvancedShader',
'Get-OBSGaussianBlurShader',
'Get-OBSGaussianBlurSimpleShader',
'Get-OBSGaussianExampleShader',
'Get-OBSGaussianSimpleShader',
'Get-OBSGbCameraShader',
'Get-OBSGlassShader',
'Get-OBSGlitchAnalogShader',
'Get-OBSGlitchPeriodicShader',
'Get-OBSGlitchShader',
'Get-OBSGlowShader',
'Get-OBSGradientShader',
'Get-OBSHalftoneShader',
'Get-OBSHardBlinkShader',
'Get-OBSHeatWaveSimpleShader',
'Get-OBSHexagonShader',
'Get-OBSHslHsvSaturationShader',
'Get-OBSHueRotatonShader',
'Get-OBSIntensityScopeShader',
'Get-OBSInvertLumaShader',
'Get-OBSLuminance2Shader',
'Get-OBSLuminanceAlphaShader',
'Get-OBSLuminanceShader',
'Get-OBSMatrixShader',
'Get-OBSMotionBlurShader',
'Get-OBSMultiplyShader',
'Get-OBSNightSkyShader',
'Get-OBSNoiseShader',
'Get-OBSNormalMapShader',
'Get-OBSOpacityShader',
'Get-OBSPagePeelShader',
'Get-OBSPagePeelTransitionShader',
'Get-OBSPerlinNoiseShader',
'Get-OBSPerspectiveShader',
'Get-OBSPieChartShader',
'Get-OBSPixelationShader',
'Get-OBSPixelationTransitionShader',
'Get-OBSPolarShader',
'Get-OBSPulseShader',
'Get-OBSQuadrilateralCropShader',
'Get-OBSRainbowShader',
'Get-OBSRainWindowShader',
'Get-OBSRectangularDropShadowShader',
'Get-OBSReflectShader',
'Get-OBSRemovePartialPixelsShader',
'Get-OBSRepeatGridCenterCropShader',
'Get-OBSRepeatShader',
'Get-OBSRepeatTextureShader',
'Get-OBSRGBAPercentShader',
'Get-OBSRgbColorWheelShader',
'Get-OBSRgbSplitShader',
'Get-OBSRgbvisibilityShader',
'Get-OBSRGSSAAShader',
'Get-OBSRippleShader',
'Get-OBSRotatingSourceShader',
'Get-OBSRotatoeShader',
'Get-OBSRoundedRect2Shader',
'Get-OBSRoundedRectPerCornerShader',
'Get-OBSRoundedRectPerSideShader',
'Get-OBSRoundedRectShader',
'Get-OBSRoundedStrokeGradientShader',
'Get-OBSRoundedStrokeShader',
'Get-OBSScanLineShader',
'Get-OBSSeascapeShader',
'Get-OBSSeasickShader',
'Get-OBSSelectiveColorShader',
'Get-OBSShakeShader',
'Get-OBSShineShader',
'Get-OBSSimpleGradientShader',
'Get-OBSSimplexNoiseShader',
'Get-OBSSmartDenoiseShader',
'Get-OBSSpecularShineShader',
'Get-OBSSpotlightShader',
'Get-OBSSwirlShader',
'Get-OBSTetraShader',
'Get-OBSThermalShader',
'Get-OBSTvCrtSubpixelShader',
'Get-OBSTwistShader',
'Get-OBSTwoPassDropShadowShader',
'Get-OBSVCRShader',
'Get-OBSVHSShader',
'Get-OBSVignettingShader',
'Get-OBSVoronoiPixelationShader',
'Get-OBSWalkingDeadPixelFixerShader',
'Get-OBSZigZagShader',
'Get-OBSZoomBlurShader',
'Get-OBSZoomBlurTransitionShader',
'Get-OBSZoomShader',
'Get-OBSZoomXYShader',
'Set-OBSAudioOutputSource',
'Set-OBSBrowserSource',
'Set-OBSColorSource',
'Set-OBSDisplaySource',
'Set-OBSMarkdownSource',
'Set-OBSMediaSource',
'Set-OBSSoundCloudSource',
'Set-OBSSwitchSource',
'Set-OBSVLCSource',
'Set-OBSWaveformSource',
'Set-OBSWindowSource'
}

